
ALTER TABLE corrections ADD COLUMN is_failed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE videos ADD COLUMN is_failed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE fiches ADD COLUMN is_failed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE exercices ADD COLUMN is_failed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE qcms ADD COLUMN is_failed BOOLEAN NOT NULL DEFAULT FALSE;
